
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ParkingLot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ParkingLot
 * 
 */
export type ParkingLotModel = runtime.Types.Result.DefaultSelection<Prisma.$ParkingLotPayload>

export type AggregateParkingLot = {
  _count: ParkingLotCountAggregateOutputType | null
  _avg: ParkingLotAvgAggregateOutputType | null
  _sum: ParkingLotSumAggregateOutputType | null
  _min: ParkingLotMinAggregateOutputType | null
  _max: ParkingLotMaxAggregateOutputType | null
}

export type ParkingLotAvgAggregateOutputType = {
  id: number | null
  capacity: number | null
}

export type ParkingLotSumAggregateOutputType = {
  id: number | null
  capacity: number | null
}

export type ParkingLotMinAggregateOutputType = {
  id: number | null
  name: string | null
  location: string | null
  capacity: number | null
}

export type ParkingLotMaxAggregateOutputType = {
  id: number | null
  name: string | null
  location: string | null
  capacity: number | null
}

export type ParkingLotCountAggregateOutputType = {
  id: number
  name: number
  location: number
  capacity: number
  _all: number
}


export type ParkingLotAvgAggregateInputType = {
  id?: true
  capacity?: true
}

export type ParkingLotSumAggregateInputType = {
  id?: true
  capacity?: true
}

export type ParkingLotMinAggregateInputType = {
  id?: true
  name?: true
  location?: true
  capacity?: true
}

export type ParkingLotMaxAggregateInputType = {
  id?: true
  name?: true
  location?: true
  capacity?: true
}

export type ParkingLotCountAggregateInputType = {
  id?: true
  name?: true
  location?: true
  capacity?: true
  _all?: true
}

export type ParkingLotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParkingLot to aggregate.
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParkingLots to fetch.
   */
  orderBy?: Prisma.ParkingLotOrderByWithRelationInput | Prisma.ParkingLotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ParkingLotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParkingLots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParkingLots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ParkingLots
  **/
  _count?: true | ParkingLotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ParkingLotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ParkingLotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParkingLotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParkingLotMaxAggregateInputType
}

export type GetParkingLotAggregateType<T extends ParkingLotAggregateArgs> = {
      [P in keyof T & keyof AggregateParkingLot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParkingLot[P]>
    : Prisma.GetScalarType<T[P], AggregateParkingLot[P]>
}




export type ParkingLotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParkingLotWhereInput
  orderBy?: Prisma.ParkingLotOrderByWithAggregationInput | Prisma.ParkingLotOrderByWithAggregationInput[]
  by: Prisma.ParkingLotScalarFieldEnum[] | Prisma.ParkingLotScalarFieldEnum
  having?: Prisma.ParkingLotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParkingLotCountAggregateInputType | true
  _avg?: ParkingLotAvgAggregateInputType
  _sum?: ParkingLotSumAggregateInputType
  _min?: ParkingLotMinAggregateInputType
  _max?: ParkingLotMaxAggregateInputType
}

export type ParkingLotGroupByOutputType = {
  id: number
  name: string
  location: string
  capacity: number
  _count: ParkingLotCountAggregateOutputType | null
  _avg: ParkingLotAvgAggregateOutputType | null
  _sum: ParkingLotSumAggregateOutputType | null
  _min: ParkingLotMinAggregateOutputType | null
  _max: ParkingLotMaxAggregateOutputType | null
}

type GetParkingLotGroupByPayload<T extends ParkingLotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParkingLotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParkingLotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParkingLotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParkingLotGroupByOutputType[P]>
      }
    >
  >



export type ParkingLotWhereInput = {
  AND?: Prisma.ParkingLotWhereInput | Prisma.ParkingLotWhereInput[]
  OR?: Prisma.ParkingLotWhereInput[]
  NOT?: Prisma.ParkingLotWhereInput | Prisma.ParkingLotWhereInput[]
  id?: Prisma.IntFilter<"ParkingLot"> | number
  name?: Prisma.StringFilter<"ParkingLot"> | string
  location?: Prisma.StringFilter<"ParkingLot"> | string
  capacity?: Prisma.IntFilter<"ParkingLot"> | number
  spots?: Prisma.ParkingSpotListRelationFilter
}

export type ParkingLotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  spots?: Prisma.ParkingSpotOrderByRelationAggregateInput
}

export type ParkingLotWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ParkingLotWhereInput | Prisma.ParkingLotWhereInput[]
  OR?: Prisma.ParkingLotWhereInput[]
  NOT?: Prisma.ParkingLotWhereInput | Prisma.ParkingLotWhereInput[]
  name?: Prisma.StringFilter<"ParkingLot"> | string
  location?: Prisma.StringFilter<"ParkingLot"> | string
  capacity?: Prisma.IntFilter<"ParkingLot"> | number
  spots?: Prisma.ParkingSpotListRelationFilter
}, "id">

export type ParkingLotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  _count?: Prisma.ParkingLotCountOrderByAggregateInput
  _avg?: Prisma.ParkingLotAvgOrderByAggregateInput
  _max?: Prisma.ParkingLotMaxOrderByAggregateInput
  _min?: Prisma.ParkingLotMinOrderByAggregateInput
  _sum?: Prisma.ParkingLotSumOrderByAggregateInput
}

export type ParkingLotScalarWhereWithAggregatesInput = {
  AND?: Prisma.ParkingLotScalarWhereWithAggregatesInput | Prisma.ParkingLotScalarWhereWithAggregatesInput[]
  OR?: Prisma.ParkingLotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ParkingLotScalarWhereWithAggregatesInput | Prisma.ParkingLotScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ParkingLot"> | number
  name?: Prisma.StringWithAggregatesFilter<"ParkingLot"> | string
  location?: Prisma.StringWithAggregatesFilter<"ParkingLot"> | string
  capacity?: Prisma.IntWithAggregatesFilter<"ParkingLot"> | number
}

export type ParkingLotCreateInput = {
  name: string
  location: string
  capacity: number
  spots?: Prisma.ParkingSpotCreateNestedManyWithoutLotInput
}

export type ParkingLotUncheckedCreateInput = {
  id?: number
  name: string
  location: string
  capacity: number
  spots?: Prisma.ParkingSpotUncheckedCreateNestedManyWithoutLotInput
}

export type ParkingLotUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  spots?: Prisma.ParkingSpotUpdateManyWithoutLotNestedInput
}

export type ParkingLotUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  spots?: Prisma.ParkingSpotUncheckedUpdateManyWithoutLotNestedInput
}

export type ParkingLotCreateManyInput = {
  id?: number
  name: string
  location: string
  capacity: number
}

export type ParkingLotUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ParkingLotUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ParkingLotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type ParkingLotAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type ParkingLotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type ParkingLotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type ParkingLotSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type ParkingLotScalarRelationFilter = {
  is?: Prisma.ParkingLotWhereInput
  isNot?: Prisma.ParkingLotWhereInput
}

export type ParkingLotCreateNestedOneWithoutSpotsInput = {
  create?: Prisma.XOR<Prisma.ParkingLotCreateWithoutSpotsInput, Prisma.ParkingLotUncheckedCreateWithoutSpotsInput>
  connectOrCreate?: Prisma.ParkingLotCreateOrConnectWithoutSpotsInput
  connect?: Prisma.ParkingLotWhereUniqueInput
}

export type ParkingLotUpdateOneRequiredWithoutSpotsNestedInput = {
  create?: Prisma.XOR<Prisma.ParkingLotCreateWithoutSpotsInput, Prisma.ParkingLotUncheckedCreateWithoutSpotsInput>
  connectOrCreate?: Prisma.ParkingLotCreateOrConnectWithoutSpotsInput
  upsert?: Prisma.ParkingLotUpsertWithoutSpotsInput
  connect?: Prisma.ParkingLotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParkingLotUpdateToOneWithWhereWithoutSpotsInput, Prisma.ParkingLotUpdateWithoutSpotsInput>, Prisma.ParkingLotUncheckedUpdateWithoutSpotsInput>
}

export type ParkingLotCreateWithoutSpotsInput = {
  name: string
  location: string
  capacity: number
}

export type ParkingLotUncheckedCreateWithoutSpotsInput = {
  id?: number
  name: string
  location: string
  capacity: number
}

export type ParkingLotCreateOrConnectWithoutSpotsInput = {
  where: Prisma.ParkingLotWhereUniqueInput
  create: Prisma.XOR<Prisma.ParkingLotCreateWithoutSpotsInput, Prisma.ParkingLotUncheckedCreateWithoutSpotsInput>
}

export type ParkingLotUpsertWithoutSpotsInput = {
  update: Prisma.XOR<Prisma.ParkingLotUpdateWithoutSpotsInput, Prisma.ParkingLotUncheckedUpdateWithoutSpotsInput>
  create: Prisma.XOR<Prisma.ParkingLotCreateWithoutSpotsInput, Prisma.ParkingLotUncheckedCreateWithoutSpotsInput>
  where?: Prisma.ParkingLotWhereInput
}

export type ParkingLotUpdateToOneWithWhereWithoutSpotsInput = {
  where?: Prisma.ParkingLotWhereInput
  data: Prisma.XOR<Prisma.ParkingLotUpdateWithoutSpotsInput, Prisma.ParkingLotUncheckedUpdateWithoutSpotsInput>
}

export type ParkingLotUpdateWithoutSpotsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ParkingLotUncheckedUpdateWithoutSpotsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ParkingLotCountOutputType
 */

export type ParkingLotCountOutputType = {
  spots: number
}

export type ParkingLotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spots?: boolean | ParkingLotCountOutputTypeCountSpotsArgs
}

/**
 * ParkingLotCountOutputType without action
 */
export type ParkingLotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLotCountOutputType
   */
  select?: Prisma.ParkingLotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ParkingLotCountOutputType without action
 */
export type ParkingLotCountOutputTypeCountSpotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParkingSpotWhereInput
}


export type ParkingLotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  location?: boolean
  capacity?: boolean
  spots?: boolean | Prisma.ParkingLot$spotsArgs<ExtArgs>
  _count?: boolean | Prisma.ParkingLotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["parkingLot"]>

export type ParkingLotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  location?: boolean
  capacity?: boolean
}, ExtArgs["result"]["parkingLot"]>

export type ParkingLotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  location?: boolean
  capacity?: boolean
}, ExtArgs["result"]["parkingLot"]>

export type ParkingLotSelectScalar = {
  id?: boolean
  name?: boolean
  location?: boolean
  capacity?: boolean
}

export type ParkingLotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "location" | "capacity", ExtArgs["result"]["parkingLot"]>
export type ParkingLotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  spots?: boolean | Prisma.ParkingLot$spotsArgs<ExtArgs>
  _count?: boolean | Prisma.ParkingLotCountOutputTypeDefaultArgs<ExtArgs>
}
export type ParkingLotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ParkingLotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ParkingLotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ParkingLot"
  objects: {
    spots: Prisma.$ParkingSpotPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    location: string
    capacity: number
  }, ExtArgs["result"]["parkingLot"]>
  composites: {}
}

export type ParkingLotGetPayload<S extends boolean | null | undefined | ParkingLotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload, S>

export type ParkingLotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ParkingLotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParkingLotCountAggregateInputType | true
  }

export interface ParkingLotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ParkingLot'], meta: { name: 'ParkingLot' } }
  /**
   * Find zero or one ParkingLot that matches the filter.
   * @param {ParkingLotFindUniqueArgs} args - Arguments to find a ParkingLot
   * @example
   * // Get one ParkingLot
   * const parkingLot = await prisma.parkingLot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ParkingLotFindUniqueArgs>(args: Prisma.SelectSubset<T, ParkingLotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ParkingLot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ParkingLotFindUniqueOrThrowArgs} args - Arguments to find a ParkingLot
   * @example
   * // Get one ParkingLot
   * const parkingLot = await prisma.parkingLot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ParkingLotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ParkingLotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParkingLot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotFindFirstArgs} args - Arguments to find a ParkingLot
   * @example
   * // Get one ParkingLot
   * const parkingLot = await prisma.parkingLot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ParkingLotFindFirstArgs>(args?: Prisma.SelectSubset<T, ParkingLotFindFirstArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ParkingLot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotFindFirstOrThrowArgs} args - Arguments to find a ParkingLot
   * @example
   * // Get one ParkingLot
   * const parkingLot = await prisma.parkingLot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ParkingLotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ParkingLotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ParkingLots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ParkingLots
   * const parkingLots = await prisma.parkingLot.findMany()
   * 
   * // Get first 10 ParkingLots
   * const parkingLots = await prisma.parkingLot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const parkingLotWithIdOnly = await prisma.parkingLot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ParkingLotFindManyArgs>(args?: Prisma.SelectSubset<T, ParkingLotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ParkingLot.
   * @param {ParkingLotCreateArgs} args - Arguments to create a ParkingLot.
   * @example
   * // Create one ParkingLot
   * const ParkingLot = await prisma.parkingLot.create({
   *   data: {
   *     // ... data to create a ParkingLot
   *   }
   * })
   * 
   */
  create<T extends ParkingLotCreateArgs>(args: Prisma.SelectSubset<T, ParkingLotCreateArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ParkingLots.
   * @param {ParkingLotCreateManyArgs} args - Arguments to create many ParkingLots.
   * @example
   * // Create many ParkingLots
   * const parkingLot = await prisma.parkingLot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ParkingLotCreateManyArgs>(args?: Prisma.SelectSubset<T, ParkingLotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ParkingLots and returns the data saved in the database.
   * @param {ParkingLotCreateManyAndReturnArgs} args - Arguments to create many ParkingLots.
   * @example
   * // Create many ParkingLots
   * const parkingLot = await prisma.parkingLot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ParkingLots and only return the `id`
   * const parkingLotWithIdOnly = await prisma.parkingLot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ParkingLotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ParkingLotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ParkingLot.
   * @param {ParkingLotDeleteArgs} args - Arguments to delete one ParkingLot.
   * @example
   * // Delete one ParkingLot
   * const ParkingLot = await prisma.parkingLot.delete({
   *   where: {
   *     // ... filter to delete one ParkingLot
   *   }
   * })
   * 
   */
  delete<T extends ParkingLotDeleteArgs>(args: Prisma.SelectSubset<T, ParkingLotDeleteArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ParkingLot.
   * @param {ParkingLotUpdateArgs} args - Arguments to update one ParkingLot.
   * @example
   * // Update one ParkingLot
   * const parkingLot = await prisma.parkingLot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ParkingLotUpdateArgs>(args: Prisma.SelectSubset<T, ParkingLotUpdateArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ParkingLots.
   * @param {ParkingLotDeleteManyArgs} args - Arguments to filter ParkingLots to delete.
   * @example
   * // Delete a few ParkingLots
   * const { count } = await prisma.parkingLot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ParkingLotDeleteManyArgs>(args?: Prisma.SelectSubset<T, ParkingLotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ParkingLots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ParkingLots
   * const parkingLot = await prisma.parkingLot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ParkingLotUpdateManyArgs>(args: Prisma.SelectSubset<T, ParkingLotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ParkingLots and returns the data updated in the database.
   * @param {ParkingLotUpdateManyAndReturnArgs} args - Arguments to update many ParkingLots.
   * @example
   * // Update many ParkingLots
   * const parkingLot = await prisma.parkingLot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ParkingLots and only return the `id`
   * const parkingLotWithIdOnly = await prisma.parkingLot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ParkingLotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ParkingLotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ParkingLot.
   * @param {ParkingLotUpsertArgs} args - Arguments to update or create a ParkingLot.
   * @example
   * // Update or create a ParkingLot
   * const parkingLot = await prisma.parkingLot.upsert({
   *   create: {
   *     // ... data to create a ParkingLot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ParkingLot we want to update
   *   }
   * })
   */
  upsert<T extends ParkingLotUpsertArgs>(args: Prisma.SelectSubset<T, ParkingLotUpsertArgs<ExtArgs>>): Prisma.Prisma__ParkingLotClient<runtime.Types.Result.GetResult<Prisma.$ParkingLotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ParkingLots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotCountArgs} args - Arguments to filter ParkingLots to count.
   * @example
   * // Count the number of ParkingLots
   * const count = await prisma.parkingLot.count({
   *   where: {
   *     // ... the filter for the ParkingLots we want to count
   *   }
   * })
  **/
  count<T extends ParkingLotCountArgs>(
    args?: Prisma.Subset<T, ParkingLotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParkingLotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ParkingLot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParkingLotAggregateArgs>(args: Prisma.Subset<T, ParkingLotAggregateArgs>): Prisma.PrismaPromise<GetParkingLotAggregateType<T>>

  /**
   * Group by ParkingLot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParkingLotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ParkingLotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ParkingLotGroupByArgs['orderBy'] }
      : { orderBy?: ParkingLotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ParkingLotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParkingLotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ParkingLot model
 */
readonly fields: ParkingLotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ParkingLot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ParkingLotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  spots<T extends Prisma.ParkingLot$spotsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ParkingLot$spotsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParkingSpotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ParkingLot model
 */
export interface ParkingLotFieldRefs {
  readonly id: Prisma.FieldRef<"ParkingLot", 'Int'>
  readonly name: Prisma.FieldRef<"ParkingLot", 'String'>
  readonly location: Prisma.FieldRef<"ParkingLot", 'String'>
  readonly capacity: Prisma.FieldRef<"ParkingLot", 'Int'>
}
    

// Custom InputTypes
/**
 * ParkingLot findUnique
 */
export type ParkingLotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter, which ParkingLot to fetch.
   */
  where: Prisma.ParkingLotWhereUniqueInput
}

/**
 * ParkingLot findUniqueOrThrow
 */
export type ParkingLotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter, which ParkingLot to fetch.
   */
  where: Prisma.ParkingLotWhereUniqueInput
}

/**
 * ParkingLot findFirst
 */
export type ParkingLotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter, which ParkingLot to fetch.
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParkingLots to fetch.
   */
  orderBy?: Prisma.ParkingLotOrderByWithRelationInput | Prisma.ParkingLotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParkingLots.
   */
  cursor?: Prisma.ParkingLotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParkingLots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParkingLots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParkingLots.
   */
  distinct?: Prisma.ParkingLotScalarFieldEnum | Prisma.ParkingLotScalarFieldEnum[]
}

/**
 * ParkingLot findFirstOrThrow
 */
export type ParkingLotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter, which ParkingLot to fetch.
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParkingLots to fetch.
   */
  orderBy?: Prisma.ParkingLotOrderByWithRelationInput | Prisma.ParkingLotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ParkingLots.
   */
  cursor?: Prisma.ParkingLotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParkingLots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParkingLots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ParkingLots.
   */
  distinct?: Prisma.ParkingLotScalarFieldEnum | Prisma.ParkingLotScalarFieldEnum[]
}

/**
 * ParkingLot findMany
 */
export type ParkingLotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter, which ParkingLots to fetch.
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ParkingLots to fetch.
   */
  orderBy?: Prisma.ParkingLotOrderByWithRelationInput | Prisma.ParkingLotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ParkingLots.
   */
  cursor?: Prisma.ParkingLotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ParkingLots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ParkingLots.
   */
  skip?: number
  distinct?: Prisma.ParkingLotScalarFieldEnum | Prisma.ParkingLotScalarFieldEnum[]
}

/**
 * ParkingLot create
 */
export type ParkingLotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * The data needed to create a ParkingLot.
   */
  data: Prisma.XOR<Prisma.ParkingLotCreateInput, Prisma.ParkingLotUncheckedCreateInput>
}

/**
 * ParkingLot createMany
 */
export type ParkingLotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ParkingLots.
   */
  data: Prisma.ParkingLotCreateManyInput | Prisma.ParkingLotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ParkingLot createManyAndReturn
 */
export type ParkingLotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * The data used to create many ParkingLots.
   */
  data: Prisma.ParkingLotCreateManyInput | Prisma.ParkingLotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ParkingLot update
 */
export type ParkingLotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * The data needed to update a ParkingLot.
   */
  data: Prisma.XOR<Prisma.ParkingLotUpdateInput, Prisma.ParkingLotUncheckedUpdateInput>
  /**
   * Choose, which ParkingLot to update.
   */
  where: Prisma.ParkingLotWhereUniqueInput
}

/**
 * ParkingLot updateMany
 */
export type ParkingLotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ParkingLots.
   */
  data: Prisma.XOR<Prisma.ParkingLotUpdateManyMutationInput, Prisma.ParkingLotUncheckedUpdateManyInput>
  /**
   * Filter which ParkingLots to update
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * Limit how many ParkingLots to update.
   */
  limit?: number
}

/**
 * ParkingLot updateManyAndReturn
 */
export type ParkingLotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * The data used to update ParkingLots.
   */
  data: Prisma.XOR<Prisma.ParkingLotUpdateManyMutationInput, Prisma.ParkingLotUncheckedUpdateManyInput>
  /**
   * Filter which ParkingLots to update
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * Limit how many ParkingLots to update.
   */
  limit?: number
}

/**
 * ParkingLot upsert
 */
export type ParkingLotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * The filter to search for the ParkingLot to update in case it exists.
   */
  where: Prisma.ParkingLotWhereUniqueInput
  /**
   * In case the ParkingLot found by the `where` argument doesn't exist, create a new ParkingLot with this data.
   */
  create: Prisma.XOR<Prisma.ParkingLotCreateInput, Prisma.ParkingLotUncheckedCreateInput>
  /**
   * In case the ParkingLot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ParkingLotUpdateInput, Prisma.ParkingLotUncheckedUpdateInput>
}

/**
 * ParkingLot delete
 */
export type ParkingLotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
  /**
   * Filter which ParkingLot to delete.
   */
  where: Prisma.ParkingLotWhereUniqueInput
}

/**
 * ParkingLot deleteMany
 */
export type ParkingLotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ParkingLots to delete
   */
  where?: Prisma.ParkingLotWhereInput
  /**
   * Limit how many ParkingLots to delete.
   */
  limit?: number
}

/**
 * ParkingLot.spots
 */
export type ParkingLot$spotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingSpot
   */
  select?: Prisma.ParkingSpotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingSpot
   */
  omit?: Prisma.ParkingSpotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingSpotInclude<ExtArgs> | null
  where?: Prisma.ParkingSpotWhereInput
  orderBy?: Prisma.ParkingSpotOrderByWithRelationInput | Prisma.ParkingSpotOrderByWithRelationInput[]
  cursor?: Prisma.ParkingSpotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParkingSpotScalarFieldEnum | Prisma.ParkingSpotScalarFieldEnum[]
}

/**
 * ParkingLot without action
 */
export type ParkingLotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParkingLot
   */
  select?: Prisma.ParkingLotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ParkingLot
   */
  omit?: Prisma.ParkingLotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParkingLotInclude<ExtArgs> | null
}
